sonar.projectKey=rajkumarvijay_job_search_frontend
sonar.organization=rajkumarvijay
sonar.projectName=Job Search Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.config.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
